name: Snake animation 🐍

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run snake animation
        run: |
          curl -o snake.svg https://raw.githubusercontent.com/Platane/snk/main/snk.svg
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
